#!/usr/bin/env python3
from __future__ import annotations

import json
import re
import subprocess
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


SKILL = Path(__file__).resolve().parents[1]
EXPECTED_IDS = [f"{value:02d}" for value in range(1, 67)]
FORBIDDEN_TEXT = (
    "generated by",
    "由 ai 生成",
    "watermark",
    "session_url",
    "chat_url",
)
FORBIDDEN_SVG_TAGS = {"image", "script", "foreignObject", "iframe"}


def load_json(relative: str):
    path = SKILL / relative
    if not path.is_file():
        raise AssertionError(f"missing required file: {relative}")
    return json.loads(path.read_text())


def assert_ids(name: str, rows: list[dict]) -> None:
    ids = [str(row["id"]) for row in rows]
    assert ids == EXPECTED_IDS, f"{name} ids mismatch: {ids}"


def local_name(tag: str) -> str:
    return tag.rsplit("}", 1)[-1]


def validate_svg(path: Path) -> None:
    text = path.read_text()
    lowered = re.sub(r"\s+", " ", text.lower())
    for marker in FORBIDDEN_TEXT:
        assert marker not in lowered, f"forbidden marker {marker!r} in {path.name}"

    root = ET.fromstring(text)
    assert local_name(root.tag) == "svg", f"not an svg root: {path.name}"
    assert root.get("viewBox") or root.get("viewbox"), f"missing viewBox: {path.name}"
    for node in root.iter():
        tag = local_name(node.tag)
        assert tag not in FORBIDDEN_SVG_TAGS, f"forbidden <{tag}> in {path.name}"
        for attr in ("href", "src"):
            value = node.get(attr, "")
            assert not value.startswith(("http://", "https://", "data:")), (
                f"external resource in {path.name}: {value[:40]}"
            )


def validate_renderer() -> None:
    renderer = SKILL / "scripts/render_lark_skill_doc.py"
    if not renderer.exists():
        return
    output = subprocess.check_output([sys.executable, str(renderer)], text=True, cwd=SKILL.parents[1])
    assert output.count("<title>") == 1
    assert output.count("<h4>") == 66
    assert output.count('<whiteboard type="svg" path="@') == 66
    assert "<img " not in output
    root = ET.fromstring(f"<root>{output}</root>")
    children = list(root)
    template_indexes = [i for i, node in enumerate(children) if node.tag == "h4"]
    assert len(template_indexes) == 66
    for index in template_indexes:
        end = next((i for i in template_indexes if i > index), len(children))
        section = children[index:end]
        assert sum(node.tag == "whiteboard" for node in section) == 1, (
            f"template without exactly one whiteboard: {children[index].text}"
        )


def main() -> None:
    prompts = load_json("references/diagram-prompts.json")
    specs = load_json("references/template-specs.json")
    manifest = load_json("assets/sample-manifest.json")["samples"]
    assert_ids("prompts", prompts)
    assert_ids("specs", specs)
    assert_ids("manifest", manifest)

    svg_files = sorted((SKILL / "assets/samples").glob("*.svg"))
    svg_ids = [path.name.split("-", 1)[0] for path in svg_files]
    assert svg_ids == EXPECTED_IDS, f"svg ids mismatch: {svg_ids}"

    for row, path in zip(manifest, svg_files):
        expected = SKILL / row["svg_path"]
        assert expected.resolve() == path.resolve(), f"manifest path mismatch: {row['id']}"
        assert row["status"] == "ready", f"asset not ready: {row['id']}"
        validate_svg(path)

    required_spec_fields = {
        "id", "slug", "category", "title", "scene", "core_conclusion", "skeleton",
        "layout", "variables", "audience", "abstraction_level", "required_inputs",
        "required_semantics", "not_for", "bad_smells", "related_templates",
    }
    for row in specs:
        assert required_spec_fields <= row.keys(), f"missing spec fields: {row['id']}"

    validate_renderer()
    print("validated prompts=66 specs=66 manifest=66 svg=66")


if __name__ == "__main__":
    main()
